name: check-korean-grammer

on:
  push:
    branches:
      - master  # default branch
      
jobs:
  Check-Korean-Grammar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Grammar Check
        uses: Kangdyu/korean-grammar-check-action@v1
        with:
          path: "."
          check: "updated"
